### PR TITLE
Fix fan stats on MacBook Pro 2018

### LINKED ISSUE #25: Please update app for MacBook Pro 2018
Hi,

Can you update the app for the new MacBook Pro 2018.
Fanspeed is now displaying -2323492 something.

Thanks.

schermafbeelding 2018-07-24 om 07 39 08

### PR DESCRIPTION
**Pull request by itaisteinherz**
I've currently only gotten the menubar app to work, but hopefully I'll get the widget working as well in a few days.
Also, there are still some bugs that need to get fixed (for examples, look at the screenshot below).
@DanielStormApps It would be great if you could help me out with this, as I have no experience in Obj-C and its APIs.

This fixes #25.

Screenshot

*Note that I don't really know Objective-C, and so if you have any suggestions as to how the PR could be improved, please let me know.*

### CODE REVIEW

**Comment by attilavago** [comment]
Downloaded the latest available version online today for my new MacBook Pro, so I can also confirm the presence of the issue. I am no ObjC expert but that code change looks sound to me. Having said that, there must be more to it, as the RPM is zero.

**Comment by deanmraz** [comment]
@DanielStormApps great work on this! hoping we can get this merged up?

**Comment by husnulhamidiah** [comment]
Can we merge this fix? The problem still exist in the latest available version online

**Comment by husnulhamidiah** [comment]
Can you share the final app, so we can use it?

**Comment by itaisteinherz** [comment]
@husnulhamidiah I can, the only thing is that this fix isn't really useful - the numbers being reported by the app are inaccurate and unreliable. There are a few more bugs that need to be figured out before this can be merged, which is why I asked @DanielStormApps for help in the first place.

**Comment by DanielStormApps** [comment]
I’ve rebuilt the app. This issue is now resolved. Thank you for opening a PR. Please open a new issue if you experience any problems with the new version.

**Pull request closed without merging**
